name: code_gen
description: Code generators for Open DICOMweb
version: 0.0.1
homepage: https://github.com/jfphilbin/code_gen
author: Jim Philbin <jfphilbin@gmail.com

environment:
  sdk: '>=1.24.2 <2.0.0'

dependencies:
#  path: ^1.4.1

dev_dependencies:
  collection: any
  tag:
    path: C:/odw/sdk/tag
    version: 0.6.3
  test: ^0.12.0
